/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todoApp;

import controller.ProjectController;
import model.Project;

public class App {
   
    public static void main(String[] args) {
        
        //ProjectController pc = new ProjectController();
        
        //Project project = new Project();
        
        //project.setName("teste");
        //project.setDescription("description");
        //pc.save(project);
        
        ProjectController pc = new ProjectController();
        
        Project project = new Project();
        project.setId(1);
        project.setName("nome alterado");
        project.setDescription("description");
        
        
      
        pc.update(project);
        
    }
}
